spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8
    username: root
    password: 1374082140
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
